#!/usr/bin/env bash
# Using bash script to install nginx and also serving a default page of Hello World!

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
