#!/usr/bin/env bash
# Using bash script to install nginx and also serving a default page of Hello World! and also handle redirection

apt-get update
apt-get -y install nginx
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo '
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location / {
		try_files $uri $uri/ =404;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

}

' > /etc/nginx/sites-available/default
service nginx restart
