#!/usr/bin/env bash
# Creating a script that runs a displays a text, traps different signals etc..

file='/var/run/myscript.pid'
echo "${BASHPID}" >> $file
i=1

while [ $i = 1 ];
do
	trap "echo Y U no love me; break" SIGINT
	trap "echo I hate the kill command; break" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done

rm $file
exit
