#!/usr/bin/env bash
# Creating a script that runs a displays a text, traps different signals etc..

file='/var/run/myscript.pid'
echo "${BASHPID}" >> $file
i=1

while [ i = 1 ];
do
	echo "To infinity and beyond"
	trap "echo Y U no love me; break" SIGINT
	trap "echo I hate the kill command; break" SIGTERM
done

rm $file
exit
