#!/usr/bin/env bash
# A bash init scripts that starts up manage_my_process script

case "$1" in
	"start")
		./manage_my_process
		touch /var/run/$!
		echo "manage_my_process started"
		;;
	"stop")
		pkill $!
		rm -f /var/run/$!
		echo "manage_my_process stopped"
		;;
	"restart")
		pkill $!
		rm -f /var/run/$!
		./manage_my_process
		touch /var/run/$!
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
	esac

