#!/usr/bin/env bash
# A bash init scripts that starts up manage_my_process script

pfile="/var/run/my_process.pid"
case "$1" in
	"start")
		./manage_my_process &
		echo $! > $pfile
		echo "manage_my_process started"
		;;
	"stop")
		kill "$(cat $pfile)"
		rm -f $pfile
		echo "manage_my_process stopped"
		;;
	"restart")
		kill "$(cat $pfile)"
		rm -f $pfile
		./manage_my_process &
		echo $! > $pfile
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
	esac

