#!/usr/bin/env bash
# Read a /etc/passwd and returning a specific info



while read -r line;
do
	echo "$(echo $line | cut -d ":" -f 1):$(echo $line | cut -d ":" -f 3):$(echo $line | cut -d ":" -f 6)"
done < "/etc/passwd"
