#!/usr/bin/env bash
# Using Ifs to read through files


filename="/etc/passwd"

while IFS=":" read -r username passwd uid gid uinfo homedir shelltype;

do 
	echo "The user "${username}" is part of the "${gid}" gang, lives in "${homedir}" and rides "${shelltype}". "${uid}"'s place is protected by the passcode "${passwd}", more info about the user here: "${uinfo}""

done < $filename
